- salem/datasets.py
- salem/tests/test_datasets.py
This was a very strange behavior of pandas (should check if it is still the case)
> bug for times including 1970

- requirements-all.txt
- salem/gis.py
fixes https://github.com/fmaussion/salem/issues/6
> bug in map_gridded_data

- docs/whats-new.rst
- salem/tests/test_misc.py
- salem/wrftools.py
> diag var: windspeed

- salem/sio.py
- salem/tests/test_misc.py
- salem/wrftools.py
An attempt to make it faster. There are probably better ways to do this (with cleverer chunks), but this still improves running time on my quadcore. In some situation, it might be slower though.
It should be tested on actual data for speed
> multiprocessing for vertical interp

- .gitignore
- LICENSE.rst
- docs/api.rst
- docs/whats-new.rst
- docs/wrf.rst
- licenses/NCL_LICENSE
- licenses/XARRAY_LICENSE
- salem/__init__.py
- salem/sio.py
- salem/tests/test_misc.py
- salem/wrftools.py
And other various bug fixes related to I/O of wrf objects
> new open_mf_wrf_dataset function

- salem/sio.py
- salem/tests/test_misc.py
This uses a dirty trick: it loads the data before concatenating, thus avoiding the concurrent access to the netcdf files...
> new way to ensure thread safety with load() in prepreprocess

- .travis.yml
- ci/requirements-py35-xarray-dev.yml
- salem/gis.py
- salem/sio.py
- salem/tests/test_gis.py
- salem/tests/test_misc.py
- salem/wrftools.py
also removed some warnings
wip with grid comparison, but it will be addressed in a following pr
> add tests for xarray dev version

- docs/examples/plot_landsea_mask.py
- salem/graphics.py
A small improvement to the docs
> Shapefile to raster example

- docs/whats-new.rst
- salem/gis.py
- salem/tests/test_gis.py
> transform_geopandas can now handle grid to proj transformations

- docs/conf.py
- docs/environment.yml
there were dependency issues with pillow on RTD
see https://github.com/conda-forge/fiona-feedstock/issues/21 for details
> Repair doc build

- docs/api.rst
- docs/examples/plot_subgrid_mask.py
- docs/whats-new.rst
- salem/__init__.py
- salem/gis.py
- salem/tests/test_gis.py
- salem/tests/test_misc.py
- salem/utils.py
>  New  reduce function + examples

- salem/graphics.py
> Add utility func to DataLevels

- .travis.yml
- docs/whats-new.rst
- salem/tests/test_misc.py
- salem/utils.py
> Pickles are now updated when pandas version changes

- docs/environment.yml
> Back to 3.5 for docs

- docs/environment.yml
- docs/examples/plot_polarstereo.py
- docs/whats-new.rst
- salem/datasets.py
- salem/gis.py
- salem/sio.py
- salem/tests/__init__.py
- salem/tests/test_datasets.py
- salem/tests/test_graphics.py
- salem/tests/test_misc.py
- salem/wrftools.py
> Support for polar stereographic WRF files

- salem/tests/test_graphics.py
> Add tolerance for image test

- docs/whats-new.rst
- salem/sio.py
- salem/wrftools.py
> Units of WRF variable PRESSURE

- docs/whats-new.rst
- salem/__init__.py
- salem/sio.py
- salem/tests/test_datasets.py
- salem/tests/test_graphics.py
- salem/tests/test_misc.py
- salem/wrftools.py
> Add "extrapolate" option to wrf vertical interpolation methods

- docs/whats-new.rst
- salem/sio.py
- salem/tests/test_misc.py
- salem/wrftools.py
> Small bugfixes in exotic WRF diag variables indexing

- docs/whats-new.rst
- salem/__init__.py
- salem/gis.py
>  Bugfix in cartopy proj conversion - WRF maps are nearly perfect now 

- docs/whats-new.rst
- salem/gis.py
- salem/tests/test_datasets.py
> Grid.ij_to_crs should now handle non numpy arrays too

- salem/sio.py
This is a very temporary solution. Ideally we should avoid using xarray's private methods altogether
> Fix AttributeError whith most recent xarray version

- salem/sio.py
> Option to specify fallback value instead of default NaN for Masking

- docs/whats-new.rst
- salem/sio.py
> What's new and small tweak to previous PR

- docs/whats-new.rst
- salem/utils.py
> Add 'nlon' nlat' to grid coordinate names

- docs/whats-new.rst
> Update docs for release

- salem/__init__.py
> Update baseline commit

- docs/examples/plot_change_style.py
- salem/graphics.py
- salem/tests/test_misc.py
> Add bounding box to scale bar

- salem/datasets.py
- salem/sio.py
- salem/tests/test_datasets.py
- salem/tests/test_gis.py
- salem/tests/test_misc.py
See: https://github.com/Unidata/netcdf4-python/issues/809
> netCDF4: set_auto_mask to False everywhere

- docs/whats-new.rst
- salem/__init__.py
- salem/gis.py
- salem/tests/test_gis.py
- salem/tests/test_graphics.py
> Add extent_as_polygon

- salem/sio.py
This PR should do the simple trick! Correct me if I'm wrong, but I think there is no specific test for this function and if the attributes are preserved, so I haven't written any either for the encoding. If you want me to, just let me know, also concerning a tiny whatsnew entry.
> Preserve encoding while making ROI

- salem/datasets.py
- salem/graphics.py
- [NA] tests added / passed
- [NA] passes ``git diff upstream/master | flake8 --diff``
- [NA] whatsnew entry
I've haven't built the docs and tested the `Note` section in `GoogleVisibleMap` to see it appears in as a 'Note box' as I was having issues building the docs with `docs/environment.yml`
> update docs (#110)

- docs/api.rst
- docs/whats-new.rst
- salem/__init__.py
- salem/gis.py
- salem/sio.py
- salem/tests/test_misc.py
- salem/utils.py
> Add minimal support for MetUm rotated grid files

- salem/datasets.py
- salem/wrftools.py
> Fix failing tests after numpy update

- .travis.yml
- ci/requirements-py36-all.yml
- docs/whats-new.rst
- salem/__init__.py
- salem/datasets.py
- salem/tests/test_misc.py
- salem/wrftools.py
fixed a bug in ``geogrid_simulator`` that would occur if `stand_lon` and `ref_lon` were not set to the same value (a strange idea tbh)
> Fix small bug in geogrid_simulator

- salem/sio.py
> metum files: also correct other lon coordinates

- ci/requirements-py27-all.yml
- ci/requirements-py36-all-rc.yml
- ci/requirements-py36-all.yml
- ci/requirements-py36-xarray-dev.yml
- salem/datasets.py
- salem/graphics.py
- salem/sio.py
- salem/tests/test_misc.py
- salem/utils.py
closes https://github.com/fmaussion/salem/issues/86
> Several fixes for upstream package updates

- .travis.yml
- ci/requirements-py36-all-xr10.yml
- salem/graphics.py
- salem/sio.py
- salem/tests/test_misc.py
closes https://github.com/fmaussion/salem/issues/127
> Fixes for xarray 0.11

- salem/gis.py
- salem/graphics.py
> Handle deprecated is_latlong on proj instances

- salem/gis.py
- salem/tests/test_gis.py
- salem/tests/test_graphics.py
- salem/tests/test_misc.py
This new version is a mess - many things are broken
> Attempts to fix issues with recent pyprojs

- salem/graphics.py
> Specify autoscale kwarg name in plot

- .travis.yml
- ci/requirements-py36-pyproj.yml
- salem/datasets.py
- salem/gis.py
- salem/sio.py
- salem/tests/test_gis.py
- salem/tests/test_misc.py
> Add test for GH152 and fix pyproj updates

- docs/environment.yml
> Add motionless to doc env

- salem/gis.py
- salem/sio.py
- salem/tests/test_gis.py
- salem/tests/test_graphics.py
- salem/tests/test_misc.py
Still pyproj and all giving headaches
> attempt to remove deprecation warnings

- docs/whats-new.rst
- salem/__init__.py
- salem/sio.py
- salem/tests/test_datasets.py
- salem/tests/test_misc.py
- salem/wrftools.py
> Add support for lossy compression on WRF files

- docs/whats-new.rst
- salem/sio.py
- setup.py
Also triggers a test with latest package version to see what's going on
> Fix issue after update in cftime

- salem/sio.py
@TimoRoth this should solve the issues in OGGM tests
> Fix backwards incompatibility issue with cftime

- salem/graphics.py
- salem/tests/test_datasets.py
> BoundaryNorm now has an extend kwarg

- salem/graphics.py
- salem/sio.py
> Fix plot bug with integer data

- salem/utils.py
I updated the url of `earth_base`, but not sure how and where to add the test function. If it's necessary, please let me know!
> update the url of earth_base

- docs/examples.rst
teeny tiny one word change but pimped made me do a double take
> minor (one word) doc change

- salem/__init__.py
- salem/sio.py
- salem/tests/test_datasets.py
- salem/wrftools.py
Thanks @matthiasdemuzere 
Added a test, and removed the geogrid simulator code that can't be tested
> Add WRF lon-lat projection

- salem/sio.py
closes https://github.com/fmaussion/salem/issues/233
I guess simplest is just to remove this and see if it occurs again
> Try to remove single thread dask
